spring:
  application:
    name: achen-fire-alarm
  datasource:
    url: jdbc:postgresql://ec2-52-202-22-140.compute-1.amazonaws.com:5432/d7q9rnfgpclu5r
    username: zghpyspjtncsde
    password: e9dc19f8a8414f1526bfa938c5f5c24ae4b6b461da579935e25930dae47f38d3
    hikari:
      connectionTimeout: 3000
      idleTimeout: 600000
      maxLifetime: 1800000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

jwt:
  secret: secret
app:
  jwtExpirationMs: 360000000

admin:
  username: admin@admin.com
  password: thinktwice